FROM ros:kinetic

LABEL maintainer="bernd.pfrommer@gmail.com"
LABEL version="1.0"
LABEL description="custom Docker Image for building multicam_calibration"

ARG DEBIAN_FRONTEND=noninteractive
# Update Ubuntu Software repository
RUN apt-get update
RUN apt-get -y install git libceres-dev

